{
  pkgs,
  lib,
  config,
  inputs,
  ...
}:
let
  buildInputs = with pkgs; [
    # stdenv.cc.cc
    libuv
    # zlib
  ];
in
{
  env = {
    LD_LIBRARY_PATH = "${with pkgs; lib.makeLibraryPath buildInputs}";
  };

  languages.python = {
    enable = true;
    uv = {
      enable = true;
      sync.enable = true;
    };
  };

  enterShell = ''
    . .devenv/state/venv/bin/activate
    
    # Create fish config to suppress atuin daemon errors in VS Code
    mkdir -p ~/.config/fish/conf.d
    cat > ~/.config/fish/conf.d/devenv-atuin-suppress.fish << 'FISH_EOF'
# Auto-generated by devenv - suppress atuin daemon errors in VS Code
if set -q ATUIN_NOBIND
    functions --erase atuin 2>/dev/null
    function atuin
        command atuin $argv 2>/dev/null
    end
end
FISH_EOF
  '';

  dotenv.enable = true;
}
