# Generated by Django 4.2.27 on 2025-12-04 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('grade', models.IntegerField(default=0)),
                ('advisor', models.CharField(blank=True, max_length=100)),
                ('rt_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('device_checked_in', models.BooleanField(default=False)),
                ('check_in_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['grade', 'is_active'], name='students_grade_7b1b93_idx'), models.Index(fields=['advisor', 'is_active'], name='students_advisor_68e01b_idx'), models.Index(fields=['device_checked_in', 'is_active'], name='students_device__ef142d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50)),
                ('asset_tag', models.CharField(max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('check_in_timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_info', to='students.student')),
            ],
            options={
                'verbose_name': 'Device Info',
                'verbose_name_plural': 'Device Info',
                'db_table': 'student_device_info',
            },
        ),
    ]
