# Generated by Django 4.2.27 on 2025-12-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grade', models.IntegerField(default=0)),
                ('rt_user_id', models.IntegerField(blank=True, null=True)),
                ('device_checked_in', models.BooleanField(default=False)),
                ('check_in_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['name'],
            },
        ),
    ]
