# Generated by Django 4.2.27 on 2025-12-03 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset_id', models.CharField(max_length=50)),
                ('asset_tag', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('previous_owner', models.CharField(blank=True, max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('ticket_id', models.CharField(blank=True, max_length=50)),
                ('needs_repair', models.BooleanField(default=False)),
                ('missing_charger', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'device_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50)),
                ('asset_tag', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('check_in_timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Device info',
                'db_table': 'device_info',
            },
        ),
    ]
