# Generated by Django 4.2.27 on 2025-12-03 13:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('creator_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('student_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'audit_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('advisor', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('audited', models.BooleanField(default=False)),
                ('audit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('auditor_name', models.CharField(blank=True, max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='audit.auditsession', to_field='session_id')),
            ],
            options={
                'db_table': 'audit_students',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator_name', models.CharField(max_length=255)),
                ('audit_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='audit.auditstudent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='audit.auditsession', to_field='session_id')),
            ],
            options={
                'db_table': 'audit_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditDeviceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50)),
                ('asset_tag', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('verification_timestamp', models.DateTimeField(blank=True, null=True)),
                ('audit_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_records', to='audit.auditstudent')),
            ],
            options={
                'db_table': 'audit_device_records',
            },
        ),
    ]
