# Generated by Django 4.2.27 on 2025-12-05 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditsession',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Teacher or admin who created the session', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
