# Generated by Django 4.2.27 on 2025-12-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditsession_closed_at_auditsession_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsession',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
