# Generated by Django 4.2.27 on 2025-12-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_audit_device_verification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditchangelog',
            new_name='audit_chang_session_99ac35_idx',
            old_name='audit_chang_session_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditchangelog',
            new_name='audit_chang_audit_s_0d2934_idx',
            old_name='audit_chang_student_timestamp_idx',
        ),
    ]
