# Generated by Django 4.2.27 on 2025-12-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_rename_audit_chang_session_timestamp_idx_audit_chang_session_99ac35_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdevicerecord',
            name='actual_owner_info',
            field=models.JSONField(blank=True, help_text='Information about the actual device owner if different from student', null=True),
        ),
        migrations.AddField(
            model_name='auditdevicerecord',
            name='owner_matches_student',
            field=models.BooleanField(default=True, help_text='Whether the device owner matches the current student'),
        ),
    ]
