# Generated by Django 4.2.27 on 2025-12-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_add_device_ownership_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditdevicerecord',
            name='actual_owner_info',
        ),
        migrations.RemoveField(
            model_name='auditdevicerecord',
            name='owner_matches_student',
        ),
    ]
