# Generated by Django 4.2.27 on 2025-12-03
# Feature: 006-google-auth - Google OAuth2 Domain-Restricted Authentication
# Task: T004 - Add google_user_id field to User model

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '__latest__'),  # Django's built-in auth app (latest migration)
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: schema_editor.execute(
                'ALTER TABLE auth_user ADD COLUMN google_user_id VARCHAR(255)'
            ),
            reverse_code=lambda apps, schema_editor: schema_editor.execute(
                'ALTER TABLE auth_user DROP COLUMN google_user_id'
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: schema_editor.execute(
                'CREATE UNIQUE INDEX idx_google_user_id ON auth_user(google_user_id) WHERE google_user_id IS NOT NULL'
            ),
            reverse_code=lambda apps, schema_editor: schema_editor.execute(
                'DROP INDEX IF EXISTS idx_google_user_id'
            ),
        ),
    ]
