# Generated by Django 4.2.27 on 2025-12-03
# Feature: 006-google-auth - Google OAuth2 Domain-Restricted Authentication
# Task: T005 - Add user_role field to User model

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_add_google_user_id'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: schema_editor.execute(
                'ALTER TABLE auth_user ADD COLUMN user_role VARCHAR(20)'
            ),
            reverse_code=lambda apps, schema_editor: schema_editor.execute(
                'ALTER TABLE auth_user DROP COLUMN user_role'
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: schema_editor.execute(
                'CREATE INDEX idx_user_role ON auth_user(user_role)'
            ),
            reverse_code=lambda apps, schema_editor: schema_editor.execute(
                'DROP INDEX idx_user_role'
            ),
        ),
    ]
